### ISSUE TITLE
Feature Request: add additional logging to debug issues

### ISSUE THREAD

**Issue by secustor** [mscharley/dependency-changesets-action#181]
I'm trying to setup this action in one my Renovate manged repositories, though it doesn't generate any changesets even while it exits with code 0. 

It would be helpful to add some logging so the decision tree can be debugged. 
https://github.com/secustor/backstage-plugins/actions/runs/9669801619/job/26677294667

**Comment by mscharley** [comment]
If you retry your job, there is a checkbox to enable debug logging. [You can also turn it on all the time.](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging)

Let me know if this is till not enough though! There's a fair bit of debug logging already enabled though.

**Comment by mscharley** [comment]
I've just pushed v1.0.11 with some better logging around this. Let me know if you're still having issues.

**Comment by secustor** [comment]
Thanks for the release, with that I have been able to move forward. 
Though it seems like it is not committing, the changes. 

https://github.com/secustor/backstage-plugins/actions/runs/9702150882/job/26777354919

Any suggestions what I can look into?

**Comment by mscharley** [comment]
It definitely *can* add commits, see https://github.com/secustor/backstage-plugins/pull/207/commits/684424ee61246b847a569ee95727374637f26dcd via https://github.com/secustor/backstage-plugins/actions/runs/9800297376/job/27061988676

For the specific build you linked though, the log says:

```
Run mscharley/dependency-changesets-action@63f9c50be694116c9a16c3d6b47e3e42a14a9424
Creating changeset: secustor/backstage-plugins#renovate/react-router-monorepo:.changeset/dependencies-GH-226.md
No package.json files were updated
```

Since no package.json files were updated, no changeset would have been created as there were no packages updated. If you check the PR, the only file which was updated was the yarn.lock file: https://github.com/secustor/backstage-plugins/pull/226/files

Since the `yarn.lock` is only relevant to the project inside the repo, it isn't a releasable change and even if it was, it isn't attributable to a specific package to do a release so there's not a lot I could even potentially do here.

**Comment by secustor** [comment]
Thx, this makes it more clear for me now!
