### ISSUE TITLE
Error: HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by cameronhunter** [mscharley/dependency-changesets-action#49]
I see this error on pull requests ([example](https://github.com/cameronhunter/async-emitter/actions/runs/6924229648/job/18833181107?pr=2)). I'm unsure what the scenario is that causes it, but I'm assuming that it's happening when trying to read the `package.json` files?

```
Error: HttpError: Resource not accessible by integration
```

**Comment by mscharley** [comment]
This is a permissions error. If you aren't using a PAT as the token (which it looks like you aren't) then the workflow still needs the `content: write` permission in order to write a commit back to the PR branch.

I would recommend using a PAT via a secret though, otherwise when the commit is pushed back to the branch no Github Actions will run. This is a security safeguard from Github. If you do use a PAT then you will need to use `pull_request_target` as [mentioned in the README](https://github.com/mscharley/dependency-changesets-action#full-workflow-example).

**Comment by cameronhunter** [comment]
Thanks for the response @mscharley. I'll read into PAT to understand what I need to do. The odd thing is that if I click the "update pull request" button on the pull request (to rebase it), then the action works and creates the changes.

Here's an example: https://github.com/cameronhunter/async-with-timeout/pull/3

**Comment by mscharley** [comment]
Yeah, part of this will be that Github intentionally nuke a lot of permissions for Dependabot PR's. I haven't fully read up on why this is, or if it's the same kind of issue as the other permissions issues I mentioned related to Github Actions generally. Either way, using a PAT should resolve the issue because they have consistent permissions wherever they are used.

You can create Personal Access Tokens here: https://github.com/settings/tokens?type=beta

Official documentation here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token

I can't remember why off-hand now, but I'm pretty sure you need to use a fine-grained token. The only permission that needs to be granted is `read and write` level access to `Contents`
