### ISSUE TITLE
The action doesn't respect the `"ignore"` field in `config.json`

### ISSUE THREAD

**Issue by filiphsps** [mscharley/dependency-changesets-action#83]
Would be really nice if the action could respect the `ignore` field in the `config.json` changeset configuration.

I might be able to look into this personally if it's not just a super simple change; let me know!

**Comment by mscharley** [comment]
So far this isn't pulling the `changesets` configuration file, but this sounds like a reasonable first thing to need it for. I don't think it should be too complicated to implement either. I'll try to take a look next week.

**Comment by mscharley** [comment]
@filiphsps can I get you to test #90 and just make sure it does what you expect it to do? I don't have any repos that are using the ignore option at the moment. You should be able to test the branch by just updating the action to use `mscharley/dependency-changesets-action@ignore-changesets-configuration` instead of whichever version number you're using currently.

**Comment by mscharley** [comment]
@filiphsps It's been a while, so I'm happy that at a minimum there's no regressions. If you do find that there's some issues with the new ignore functionality then please feel free to log a bug. This has now been released in `v1.0.7`.
